export const books = [
    { id: 1, title: 'Bumi', author: 'Tere Liye', year: 2014 },
    { id: 2, title: 'Laskar Pelangi', author: 'Andrea Hirata', year: 2005 },
    { id: 3, title: 'Negeri 5 Menara', author: 'Ahmad Fuadi', year: 2009 },
    { id: 4, title: 'Ayat-Ayat Cinta', author: 'Habiburrahman El Shirazy', year: 2004 },
    { id: 5, title: 'Perahu Kertas', author: 'Dee Lestari', year: 2009 },
    { id: 6, title: 'Supernova', author: 'Dee Lestari', year: 2001 },
    { id: 7, title: 'Dilan 1990', author: 'Pidi Baiq', year: 2014 },
    { id: 8, title: 'Hujan', author: 'Tere Liye', year: 2016 },
    { id: 9, title: 'Sang Pemimpi', author: 'Andrea Hirata', year: 2006 },
    { id: 10, title: 'Ronggeng Dukuh Paruk', author: 'Ahmad Tohari', year: 1982 },
    { id: 11, title: 'Bumi Manusia', author: 'Pramoedya Ananta Toer', year: 1980 },
    { id: 12, title: 'Gadis Pantai', author: 'Pramoedya Ananta Toer', year: 1962 },
    { id: 13, title: 'Pulang', author: 'Tere Liye', year: 2015 },
    { id: 14, title: 'Daun yang Jatuh Tak Pernah Membenci Angin', author: 'Tere Liye', year: 2010 },
    { id: 15, title: 'Tentang Kamu', author: 'Tere Liye', year: 2016 },
    { id: 16, title: 'Edensor', author: 'Andrea Hirata', year: 2007 },
    { id: 17, title: 'Maryamah Karpov', author: 'Andrea Hirata', year: 2008 },
    { id: 18, title: 'Ranah 3 Warna', author: 'Ahmad Fuadi', year: 2011 },
    { id: 19, title: 'Cinta di Ujung Sajadah', author: 'Asma Nadia', year: 2008 },
    { id: 20, title: 'Ketika Cinta Bertasbih', author: 'Habiburrahman El Shirazy', year: 2007 },
  ]

  export const users = [
    { id: 1, name: 'Budi Santoso', email: 'budi@gmail.com', role: 'ADMIN' },
    { id: 2, name: 'Siti Rahayu', email: 'siti.rahayu@gmail.com', role: 'ADMIN' },
    { id: 3, name: 'Agus Permana', email: 'agus.permana@gmail.com', role: 'ADMIN' },
    { id: 4, name: 'Dewi Kusuma', email: 'dewi.kusuma@gmail.com', role: 'USER' },
    { id: 5, name: 'Rizky Pratama', email: 'rizky.pratama@gmail.com', role: 'USER' },
    { id: 6, name: 'Nur Fadilah', email: 'nur.fadilah@gmail.com', role: 'USER' },
    { id: 7, name: 'Eko Wahyudi', email: 'eko.wahyudi@gmail.com', role: 'USER' },
    { id: 8, name: 'Putri Handayani', email: 'putri.handayani@gmail.com', role: 'USER' },
    { id: 9, name: 'Fajar Nugroho', email: 'fajar.nugroho@gmail.com', role: 'USER' },
    { id: 10, name: 'Lestari Wulandari', email: 'lestari.wulandari@gmail.com', role: 'USER' },
    { id: 11, name: 'Hendra Gunawan', email: 'hendra.gunawan@gmail.com', role: 'USER' },
    { id: 12, name: 'Mega Pertiwi', email: 'mega.pertiwi@gmail.com', role: 'USER' },
    { id: 13, name: 'Dandi Setiawan', email: 'dandi.setiawan@gmail.com', role: 'USER' },
    { id: 14, name: 'Rini Anggraini', email: 'rini.anggraini@gmail.com', role: 'USER' },
    { id: 15, name: 'Yusuf Hidayat', email: 'yusuf.hidayat@gmail.com', role: 'USER' },
    { id: 16, name: 'Ayu Fitriani', email: 'ayu.fitriani@gmail.com', role: 'USER' },
    { id: 17, name: 'Bagas Saputro', email: 'bagas.saputro@gmail.com', role: 'USER' },
    { id: 18, name: 'Indah Suryani', email: 'indah.suryani@gmail.com', role: 'USER' },
    { id: 19, name: 'Wahyu Kurniawan', email: 'wahyu.kurniawan@gmail.com', role: 'USER' },
    { id: 20, name: 'Fitri Rahmawati', email: 'fitri.rahmawati@gmail.com', role: 'USER' },
  ]